GET http://localhost:3000/posts
Authorization: Bearer firsthere

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "criss"
}

###

DELETE http://localhost:4000/logout Content-Type: application/json

{
"token": "refresh token inside"
}

###
POST http://localhost:4000/token Content-Type: application/json

{
"token": "Refere"
}